spring.application.name=booking-system
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=B8PdKDqK/gxnuN2f18bC5fNvIjrvo5q50beWNHtVtOJfaM+u3/ErH0qKOQDfdMceMGb0qxhxQBLT2Jk2DTH+HA==
jwt.expiration=3600000