services:
  postgres:
    image: postgres:18
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql

volumes:
  booking-db-data: