spring.profiles.include=local

spring.application.name=booking-system
spring.datasource.url=${POSTGRE_URL}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=3600000